version: '3.1'
services:
  database:
    container_name: database_java
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER : ${root}
      POSTGRES_PASSWORD: ${root}
      POSTGRES_DB: ${database_java}
    ports:
      - "5432:5432"
